/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Identity {
  displayName: string;
  email: (string | null);
  id: string;
  permissions: Array<string>;
  roles: Array<string>;
  scopes: Array<string>;
  sessionExpiresAt: string;
  status: 'PENDIENTE' | 'ACTIVA' | 'SUSPENDIDA' | 'DESACTIVADA';
}
