/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProblemDetails {
  code: string;
  correlationId: string;
  detail: string;
  instance: string;
  status: number;
  title: string;
  type: 'about:blank';
}
